//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CAPStageMapping
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int JobTypeId { get; set; }
        public int SD_Stage_No { get; set; }
        public string StageDescription { get; set; }
        public string DatabaseMap { get; set; }
    
        public virtual T_Department M_Department { get; set; }
        public virtual T_JobType M_JobType { get; set; }
    }
}
