//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Holiday
    {
        public int Id { get; set; }
        public int HolidayYear { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public string Description { get; set; }
    }
}
