//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JobTypeFlow
    {
        public int Id { get; set; }
        public int JobTypeId { get; set; }
        public int JobFlowId { get; set; }
        public int Position { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual T_JobFlow M_JobFlow { get; set; }
        public virtual T_JobType M_JobType { get; set; }
        public virtual T_Department M_Department { get; set; }
    }
}
