//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JobType
    {
        public T_JobType()
        {
            this.M_JobTrackers = new HashSet<T_JobTracker>();
            this.M_JobTrackerHistories = new HashSet<T_JobTrackerHistory>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> RequiredJobId { get; set; }
        public Nullable<bool> ComputeTime { get; set; }
    
        public virtual T_Department M_Department { get; set; }
        public virtual ICollection<T_JobTracker> M_JobTrackers { get; set; }
        public virtual ICollection<T_JobTrackerHistory> M_JobTrackerHistories { get; set; }
    }
}
