//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Modules
    {
        public T_Modules()
        {
            this.M_RolesModuleAccesses = new HashSet<T_RolesModuleAccess>();
        }
    
        public int Id { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public string ModuleType { get; set; }
        public Nullable<int> ArrangementOrder { get; set; }
    
        public virtual ICollection<T_RolesModuleAccess> M_RolesModuleAccesses { get; set; }
    }
}
