//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OTRateSetting
    {
        public int Id { get; set; }
        public decimal OTExemptedSalary { get; set; }
        public decimal ExemptedSalaryIncentive { get; set; }
        public double OTNormalRate { get; set; }
        public double OTSpecialRate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
