//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Roles
    {
        public T_Roles()
        {
            this.M_RoleDepartmentAccesses = new HashSet<T_RoleDepartmentAccess>();
            this.M_RolesModuleAccesses = new HashSet<T_RolesModuleAccess>();
            this.M_Users = new HashSet<T_Users>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
    
        public virtual ICollection<T_RoleDepartmentAccess> M_RoleDepartmentAccesses { get; set; }
        public virtual ICollection<T_RolesModuleAccess> M_RolesModuleAccesses { get; set; }
        public virtual ICollection<T_Users> M_Users { get; set; }
    }
}
