//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TimeClock
    {
        public int Id { get; set; }
        public int EmployeeNumber { get; set; }
        public System.DateTime ScanTime { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Filename { get; set; }
    }
}
