//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserRateSchedule
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal Salary { get; set; }
        public int OffDay { get; set; }
        public int SpecialOffDay { get; set; }
        public bool NoOTPay { get; set; }
        public bool IsCurrentRate { get; set; }
        public Nullable<int> MinsBreak { get; set; }
        public Nullable<bool> IsOfficeWorker { get; set; }
        public Nullable<int> OptionalOffDay1 { get; set; }
        public Nullable<int> OptionalOffDay2 { get; set; }
        public Nullable<int> OptionalOffDay3 { get; set; }
        public Nullable<int> OptionalOffDay4 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> UsePattern { get; set; }
        public string OffPattern { get; set; }
        public Nullable<System.DateTime> PatternStartDate { get; set; }
    
        public virtual T_Users M_User { get; set; }
    }
}
