//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public T_Users()
        {
            this.M_JobTrackerSupervisors = new HashSet<T_JobTracker>();
            this.M_JobTrackersUsers = new HashSet<T_JobTracker>();
            this.M_JobTrackerHistorySupervisors = new HashSet<T_JobTrackerHistory>();
            this.M_JobTrackerHistoryUsers = new HashSet<T_JobTrackerHistory>();
            this.M_SupervisorMappingSupervisors = new HashSet<T_SupervisorMapping>();
            this.M_SupervisorMappingUsers = new HashSet<T_SupervisorMapping>();
            this.M_TimeSettings = new HashSet<T_TimeSetting>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string Password { get; set; }
    
        public virtual T_Department M_Department { get; set; }
        public virtual ICollection<T_JobTracker> M_JobTrackerSupervisors { get; set; }
        public virtual ICollection<T_JobTracker> M_JobTrackersUsers { get; set; }
        public virtual ICollection<T_JobTrackerHistory> M_JobTrackerHistorySupervisors { get; set; }
        public virtual ICollection<T_JobTrackerHistory> M_JobTrackerHistoryUsers { get; set; }
        public virtual T_Roles M_Role { get; set; }
        public virtual ICollection<T_SupervisorMapping> M_SupervisorMappingSupervisors { get; set; }
        public virtual ICollection<T_SupervisorMapping> M_SupervisorMappingUsers { get; set; }
        public virtual ICollection<T_TimeSetting> M_TimeSettings { get; set; }
    }
}
