//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserRateSchedule
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> BaseRate { get; set; }
        public Nullable<double> OTRate { get; set; }
        public Nullable<double> SpecialRate { get; set; }
        public Nullable<bool> IsCurrentRate { get; set; }
    
        public virtual T_Users M_User { get; set; }
    }
}
