//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackerEntities : DbContext
    {
        public TimeTrackerEntities()
            : base("name=TimeTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Department> T_Department { get; set; }
        public DbSet<T_JobTracker> T_JobTracker { get; set; }
        public DbSet<T_JobTrackerHistory> T_JobTrackerHistory { get; set; }
        public DbSet<T_JobType> T_JobType { get; set; }
        public DbSet<T_JobTypeDepartment> T_JobTypeDepartment { get; set; }
        public DbSet<T_Modules> T_Modules { get; set; }
        public DbSet<T_RoleDepartmentAccess> T_RoleDepartmentAccess { get; set; }
        public DbSet<T_Roles> T_Roles { get; set; }
        public DbSet<T_RolesModuleAccess> T_RolesModuleAccess { get; set; }
        public DbSet<T_SupervisorMapping> T_SupervisorMapping { get; set; }
        public DbSet<T_TimeSetting> T_TimeSetting { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
        public DbSet<T_JobFlow> T_JobFlow { get; set; }
        public DbSet<T_JobTypeFlow> T_JobTypeFlow { get; set; }
        public DbSet<T_TimeClock> T_TimeClock { get; set; }
        public DbSet<T_CAPStageMapping> T_CAPStageMapping { get; set; }
        public DbSet<T_Holiday> T_Holiday { get; set; }
        public DbSet<T_UserRateSchedule> T_UserRateSchedule { get; set; }
        public DbSet<T_OTRateSetting> T_OTRateSetting { get; set; }
    }
}
